// <auto-generated />
namespace SkiVerleih.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsRentedStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsRentedStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202003061130023_IsRentedStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
